// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACfWBVkNaubZ0NZ4wiVkJBBstwnDscf1g',
    appId: '1:469139180349:web:d30a85b63a59ebc53e9354',
    messagingSenderId: '469139180349',
    projectId: 'testapp-c7c20',
    authDomain: 'testapp-c7c20.firebaseapp.com',
    storageBucket: 'testapp-c7c20.firebasestorage.app',
    measurementId: 'G-DG8T3W230R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQzR2E7jdocHKzXfAu8Ibxwj2phL9_uo',
    appId: '1:469139180349:android:c7427ba9da65ce013e9354',
    messagingSenderId: '469139180349',
    projectId: 'testapp-c7c20',
    storageBucket: 'testapp-c7c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWN4iFKf0HV5Z1XhNP3mVoAwNhZe2wrh8',
    appId: '1:469139180349:ios:3202def4792ad1893e9354',
    messagingSenderId: '469139180349',
    projectId: 'testapp-c7c20',
    storageBucket: 'testapp-c7c20.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWN4iFKf0HV5Z1XhNP3mVoAwNhZe2wrh8',
    appId: '1:469139180349:ios:3202def4792ad1893e9354',
    messagingSenderId: '469139180349',
    projectId: 'testapp-c7c20',
    storageBucket: 'testapp-c7c20.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACfWBVkNaubZ0NZ4wiVkJBBstwnDscf1g',
    appId: '1:469139180349:web:fb222e8b35841c9b3e9354',
    messagingSenderId: '469139180349',
    projectId: 'testapp-c7c20',
    authDomain: 'testapp-c7c20.firebaseapp.com',
    storageBucket: 'testapp-c7c20.firebasestorage.app',
    measurementId: 'G-TW3VQP8XPD',
  );
}
